### PR TITLE
Add remaining Eth JSON-RPC methods

### PR DESCRIPTION
**Pull request by loredanacirstea**
Now, all methods are listed, in accordance with https://github.com/ethereum/wiki/wiki/JSON-RPC.

### CODE REVIEW

**Comment by loredanacirstea** [comment]
Next week, I hope to start writing some tests for them.

**Comment by zot** [comment]
Wow, looks great! The changes appear to be correct, just from looking at them, but tests are indeed better than just  eyeballing them.

It appears that the Web 3 Foundation is unfortunately [abandoning Whisper](https://github.com/w3f/messaging/#whisper):

> Unfortunately, the evolution and adoption of Whisper has been stunted, which is despite the rapid advancement of applications. The lack of development means that Whisper is not able to provide the scaling that we need, nor is it feasible for projects to create their own bespoke messaging protocol. What we really need is a new protocol to handle transient messaging at scale. We believe this is a necessary cornerstone for enabling the mainstream adoption of DApps.

I used Whisper in a 2-player Ethereum-based and I do like the idea of Whisper so it's a shame to see it go. Any p2p messaging would have worked for the purposes of the game, though, so [libp2p](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md) will be sufficient for that, if the JSON API exposes enough functionality.

**Comment by loredanacirstea** [comment]
@zot , True. I thought it best to follow the current standards from https://github.com/ethereum/wiki/wiki/JSON-RPC, without making value judgments, also considering that:
- web3.js has whisper support https://web3js.readthedocs.io/en/v1.2.7/web3-shh.html
- web3.py has whisper support https://web3py.readthedocs.io/en/stable/search.html?q=shh&check_keywords=yes&area=default#
- ethers.js - doesn't have whisper support (https://github.com/ethers-io/ethers.js/issues/170#issuecomment-399647813)

But you can make value judgments, so if there are other methods aside from shh* that you don't want to be included, let me know.

**Comment by zot** [comment]
I'm happy to include them, I wanted to make sure you and your org knew about shh though, in case you are planning to depend on them

**Comment by zot** [comment]
Sheesh, I thought I merged this already...

**Comment by zot** [comment]
Sorry about that -- merged :)

**Pull request merged**
