### PR TITLE
Extend Web3.jl with support for additional RPC calls

### PR DESCRIPTION
**Pull request by loredanacirstea**
Thank you for resolving https://github.com/lambda-mechanics/Web3.jl/issues/2.
I have picked up the task to help with extending Web3.jl, at least as much as we also need.

New to Julia, so I would appreciate some pointers, hence the Draft.

### CODE REVIEW

**Comment by loredanacirstea** [comment]
Update - disregard the following. I was not paying attention that I was jamming a `dict` into a string concatenation.

Do you know why the RPC calls that return more than a string, fail? E.g. `gettransactionbyhash` or `gettransactionreceipt`.

From:
```
apifunc(apimethod, func) = (con::Web3Connection, args...; raw=false)-> (raw ? rawjsonget : jsonget)(con.url, apimethod, func(args...)...)
```
, I would have expected the RPC call result to be directly passed to where the wrapped method was called.

But it fails after exiting `jsonget`:
```
RESULT JSON: {"jsonrpc":"2.0","result":{"hash":"0x25b23c0d5edfa8433388bbb3e3ae2f76feed4495038fcbdf376b252c9ede18fd","nonce":"0x4","blockHash":"0x6e89e4ba74265a1ef762095428e7b954b40e2b2085b02e00f837a935f1a13119","blockNumber":"0x5","transactionIndex":"0x0","from":"0x79f379cebbd362c99af2765d1fa541415aa78508","to":"0x04ca854d2003ec7d7f977f947a4935733d2a8181","value":"0x0","gas":"0x30d40","gasPrice":"0x4a817c800","input":"0xc9f016f70000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000164000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016600000000000000000000000000000000000000000000000000000000000000","v":"0x26","r":"0xcfe60f186ff5030dda3e9884c397fb8c8fa6f0d6a5a4c365c54561bc46dab9a0","s":"0x1633753045bab68cfca842b1454ed5a8a4fa42e5c2a7e7ce035ea1db979ebc6a"}}
RESULT: Dict{String,Any}("jsonrpc" => "2.0","result" => Dict{String,Any}("gasPrice" => "0x4a817c800","r" => "0xcfe60f186ff5030dda3e9884c397fb8c8fa6f0d6a5a4c365c54561bc46dab9a0","blockNumber" => "0x5","value" => "0x0","gas" => "0x30d40","s" => "0x1633753045bab68cfca842b1454ed5a8a4fa42e5c2a7e7ce035ea1db979ebc6a","v" => "0x26","hash" => "0x25b23c0d5edfa8433388bbb3e3ae2f76feed4495038fcbdf376b252c9ede18fd","transactionIndex" => "0x0","input" => "0xc9f016f70000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000164000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016600000000000000000000000000000000000000000000000000000000000000","blockHash" => "0x6e89e4ba74265a1ef762095428e7b954b40e2b2085b02e00f837a935f1a13119","to" => "0x04ca854d2003ec7d7f977f947a4935733d2a8181","from" => "0x79f379cebbd362c99af2765d1fa541415aa78508","nonce" => "0x4"))
JSON: Dict{String,Any}("jsonrpc" => "2.0","result" => Dict{String,Any}("gasPrice" => "0x4a817c800","r" => "0xcfe60f186ff5030dda3e9884c397fb8c8fa6f0d6a5a4c365c54561bc46dab9a0","blockNumber" => "0x5","value" => "0x0","gas" => "0x30d40","s" => "0x1633753045bab68cfca842b1454ed5a8a4fa42e5c2a7e7ce035ea1db979ebc6a","v" => "0x26","hash" => "0x25b23c0d5edfa8433388bbb3e3ae2f76feed4495038fcbdf376b252c9ede18fd","transactionIndex" => "0x0","input" => "0xc9f016f70000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000164000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016600000000000000000000000000000000000000000000000000000000000000","blockHash" => "0x6e89e4ba74265a1ef762095428e7b954b40e2b2085b02e00f837a935f1a13119","to" => "0x04ca854d2003ec7d7f977f947a4935733d2a8181","from" => "0x79f379cebbd362c99af2765d1fa541415aa78508","nonce" => "0x4"))
MethodError: no method matching *(::String, ::Dict{String,Any})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(::Union{AbstractChar, AbstractString}, !Matched::Union{AbstractChar, AbstractString}...) at strings/basic.jl:231
  *(::Union{Regex, AbstractChar, AbstractString}, !Matched::Union{Regex, AbstractChar, AbstractString}...) at regex.jl:640
  ...

Stacktrace:
 [1] top-level scope at In[122]:47
```

**Comment by zot** [comment]
I did have an error in
```
    gettransactionbyhash = apifunc(:eth_getTransactionByHash, (hash)-> (hash)),
```
It should be:
```
    gettransactionbyhash = apifunc(:eth_getTransactionByHash, (hash)-> (hash,)),
```
By leaving out the comma, it was equivalent to just `hash`, instead of a tuple.

Your change to arrays works too -- I have no idea which is more efficient. I suspect tuples are, since they are immutable and probably just live pushed on the stack but I don't actually have any evidence for that. And anyway, the time it takes to create a tuple or an array is just peanuts compared to the time it takes for a socket request, so the difference doesn't matter one bit.

Stylistically though, I do prefer tuples for this, since we're transforming argument lists and argument lists are very tupley. :)

So I think your changes are good but if you don't mind, I'll just change them from arrays to tuples after I merge.

Good?

**Comment by loredanacirstea** [comment]
@zot , no problem, I used `(hash,)`.
I did not test all the methods yet, but those mentioned in `dumpContract.jl` should work.

**Review by zot — APPROVED** [review]

**Comment by zot** [comment]
I merged and added commas to the tuples in getblocktransactioncountbyhash and getblocktransactioncountbynumber. I tested getblocktransactioncountbynumber and it failed when the function returned `(tag)` instead of `(tag,)`. Also, I exported the `net` constant.

Julia's syntax for 1-element tuples is weird but what can you to when parentheses are overloaded like that?

**Comment by loredanacirstea** [comment]
@zot , I see. Also, I didn't manage to set up a comfortable environment for running the project yet (docs are a bit confusing for first-timers) - I used Jupyter Labs. So, I expected some possible bugs ...
I will continue this when I have time - there are other functions that I would implement.

**Comment by zot** [comment]
Personally, I use emacs but I think a lot of Julia people use Juno, which is Electron-based. Electron is really nice but the fundamental versatility of Emacs is really hard to beat and I always end up missing it in other environments.

I don't use Julia very much these days but I'm hoping that will change because it really is my current favorite programming language!

**Pull request merged**
